


#上传文件地址
web:
  upload-path: /Users/fishfly/localFile

#服务器ip 处理静态文件上传
serverIP: localhost


spring:
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: false
  resources:
    static-locations: classpath:static/ ,file:${web.upload-path}
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb


server:
  port: 8089

